name: Run HelloWorld

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Compile HelloWorld.c
      run: gcc HelloWorld.c -o HelloWorld

    - name: Run HelloWorld
      run: ./HelloWorld
